### PR TITLE
AB#3276 -- Added dob errror message if user is over 150 years old

### PR DESCRIPTION
**Pull request by AdamP-HRSDC-RHDCC**
### Description
Added dob errror message if user is over 150 years old

### Related Azure Boards Work Items
[AB#3276](https://dev.azure.com/DTS-STN/1fc40a8f-28cf-47bc-b6e4-1c234bd06177/_workitems/edit/3276)

### Screenshots (if applicable)
image

### Checklist
- [x] I have tested the changes locally
- [x] I have updated the documentation if necessary
- [ ] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

### Test Instructions
Year must be greater or equal to 1874  (150 ans et toutes ses dents)

### Additional Notes
n/a

### CODE REVIEW

**Review by gregory-j-baker — APPROVED** [review]

**Comment by gregory-j-baker** [comment]
```
 FAIL  __tests__/routes/_public+/date-of-birth.test.tsx > _public.apply.id.date-of-birth > action() > should redirect to error page if dob is under 65 years
AssertionError: expected '/en/apply/123/applicant-information' to be '/en/apply/123/dob-eligibility' // Object.is equality
- Expected
+ Received
- /en/apply/123/dob-eligibility
+ /en/apply/123/applicant-information
 ❯ __tests__/routes/_public+/date-of-birth.test.tsx:128:48
    126| 
    127|       expect(response.status).toBe(302);
    128|       expect(response.headers.get('location')).toBe('/en/apply/123/dob…
       |                                                ^
    129|       expect(parse).toBeCalled();
    130|       expect(differenceInYears).toBeCalled();
```

**Comment by AdamP-HRSDC-RHDCC** [comment]
> ```
>  FAIL  __tests__/routes/_public+/date-of-birth.test.tsx > _public.apply.id.date-of-birth > action() > should redirect to error page if dob is under 65 years
> AssertionError: expected '/en/apply/123/applicant-information' to be '/en/apply/123/dob-eligibility' // Object.is equality
> - Expected
> + Received
> - /en/apply/123/dob-eligibility
> + /en/apply/123/applicant-information
>  ❯ __tests__/routes/_public+/date-of-birth.test.tsx:128:48
>     126| 
>     127|       expect(response.status).toBe(302);
>     128|       expect(response.headers.get('location')).toBe('/en/apply/123/dob…
>        |                                                ^
>     129|       expect(parse).toBeCalled();
>     130|       expect(differenceInYears).toBeCalled();
> ```

Added mockReturnValueOnce twice to fix

**Review by sebastien-comeau — COMMENTED** [review]
Consider adding the same validation for the partner dob. Can be done in another PR.

**Comment by AdamP-HRSDC-RHDCC** [comment]
> Consider adding the same validation for the partner dob. Can be done in another PR.

Extended it to the partner date of birth as well (same PR)

**Review by gregory-j-baker — APPROVED** [review]

**Pull request merged**
