### PR TITLE
AB#3066 -- event logging

### PR DESCRIPTION
**Pull request by gregory-j-baker**
### Description

The SA&A process requires that we audit important system events. This is an incremental PR that adds some event logging to the application.

### Related Azure Boards Work Items

- [AB#3066](https://dev.azure.com/DTS-STN/1fc40a8f-28cf-47bc-b6e4-1c234bd06177/_workitems/edit/3066)

### Logged audit events sample

```
2024-03-16T14:20:36.294Z    INFO --- [     audit-service.server]: {"eventId":"auth.session-created","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:20:36.294Z"}
2024-03-16T14:24:12.438Z    INFO --- [     audit-service.server]: {"eventId":"auth.session-destroyed","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:24:12.438Z"}
2024-03-16T14:28:07.499Z    INFO --- [     audit-service.server]: {"eventId":"page-view.home","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:28:07.499Z"}
2024-03-16T14:29:44.480Z    INFO --- [     audit-service.server]: {"eventId":"page-view.personal-information","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:29:44.480Z"}
2024-03-16T14:33:04.135Z    INFO --- [     audit-service.server]: {"eventId":"update-data.phone-number","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:33:04.135Z"}
2024-03-16T14:36:42.830Z    INFO --- [     audit-service.server]: {"eventId":"update-data.home-address","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:36:42.830Z"}
2024-03-16T14:35:04.575Z    INFO --- [     audit-service.server]: {"eventId":"update-data.mailing-address","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:35:04.575Z"}
2024-03-16T14:39:05.226Z    INFO --- [     audit-service.server]: {"eventId":"page-view.letters","userId":"00000000-0000-0000-0000-000000000000","timestamp":"2024-03-16T14:39:05.226Z"}
```

### Checklist

- [x] I have tested the changes locally
- [x] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

### Additional Notes

- Some tests had to be modified to accommodate these changes
- Audit events need to be added for /apply pages in a future PR

### CODE REVIEW

**Comment by sebastien-comeau** [comment]
I'm concerned by potentially log user's information.

**Comment by gregory-j-baker** [comment]
> I'm concerned by potentially log user's information.

I intentionally omitted everything but the user id.

**Comment by sebastien-comeau** [comment]
> > I'm concerned by potentially log user's information.
> 
> I intentionally omitted everything but the user id.

Since it's logged... someone could take that userId and fetch information from Interop, right?

**Comment by gregory-j-baker** [comment]
> > > I'm concerned by potentially log user's information.
> > 
> > 
> > I intentionally omitted everything but the user id.
> 
> Since it's logged... someone could take that userId and fetch information from Interop, right?

Perhaps.. not sure how we can log who accessed what without logging some user id, though.

**Comment by sebastien-comeau** [comment]
> > > > I'm concerned by potentially log user's information.
> > > 
> > > 
> > > I intentionally omitted everything but the user id.
> > 
> > 
> > Since it's logged... someone could take that userId and fetch information from Interop, right?
> 
> Perhaps.. not sure how we can log who accessed what without logging some user id, though.

You should ask IT security and privacy. 🤷

**Review by sebastien-comeau — APPROVED** [review]
Approve for now... You need to take a note to ask higher management.

**Pull request merged**
