### PR TITLE
Add lookup server utils to unify localization and sorting regions lookup

### PR DESCRIPTION
**Pull request by sebastien-comeau**
### Description

Add lookup server utils to unify localization and sorting regions lookup within the application.

### Checklist

- [x] I have tested the changes locally
- [x] I have updated the documentation if necessary
- [x] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

### CODE REVIEW

**Review by Fbasham — COMMENTED** [review]
Something I noticed:
image

The original sort allowed for `sensitivity: 'base'` in the `localeCompare`.  I don't know if there's anything similar in moderndash

**Comment by sebastien-comeau** [comment]
> The original sort allowed for `sensitivity: 'base'` in the `localeCompare`. I don't know if there's anything similar in moderndash

Now I remember why you switched to `localeCompare`. Thanks, will fix.

**Comment by sebastien-comeau** [comment]
@Fbasham I fixed it :)

**Review by Fbasham — APPROVED** [review]
looks good

**Review by gregory-j-baker — APPROVED** [review]

**Pull request merged**
