### PR TITLE
Rename `env-utils.ts` → `env-utils.client.ts`

### PR DESCRIPTION
**Pull request by gregory-j-baker**
Since `env-utils.ts` references `window.env`, it should only be used client-side. Any server-side code that needs access to the environment can use `env.server.ts`.

This PR is to support migrating to vite, PR #2009, to make that PR a little smaller.

### Checklist

- [ ] I have tested the changes locally
- [x] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

### CODE REVIEW

**Review by sebastien-comeau — COMMENTED** [review]
Have you tested it? You need to be cautious with client-only code, as the code within this file can only be executed on the client side, not the server side. Even if it's within a page React component, that code might still be called on the server for SSR (Server-Side Rendering).

Run the application and go to http://localhost:3000/en/home.

image

This is the line that cause that issue since NavigationMenu is executed server-side (SSR) and client-side: https://github.com/DTS-STN/canadian-dental-care-plan/blob/44e582932767480edb3b37144f65f480a435233a/frontend/app/components/layouts/protected-layout.tsx#L60

**Comment by gregory-j-baker** [comment]
I assumed that because the e2e tests passed, we were good. What's the point of having e2e tests if they can't detect something as trivial as your comment?

Anyway, I'll take a look.

**Comment by sebastien-comeau** [comment]
> I assumed that because the e2e tests passed, we were good. What's the point of having e2e tests if they can't detect something as trivial as your comment?
> 
> Anyway, I'll take a look.

I get your point but the page load even though it returns a 500. 🤷

**Comment by gregory-j-baker** [comment]
Closing this PR.. it is no longer necessary thanks to #2082.

**Pull request closed without merging**
