### PR TITLE
change e2e folder structure

### PR DESCRIPTION
**Pull request by Fbasham**
Change the folder structure of end-to-end tests to match remix-flat-routes style like how unit tests and the application itself are currently structured.

### CODE REVIEW

**Review by sebastien-comeau — APPROVED** [review]

**Comment by Fbasham** [comment]
> Can we match the exact structure and names of the unit tests and routes directory?
> 
> **e2e structure in this branch:** image
> 
> **Unit tests structure:** image

Oh yeah..derp.  I'm totally on auto-pilot right now.

**Comment by sebastien-comeau** [comment]
> Can we match the exact structure and names of the unit tests and routes directory?
> 
> **e2e structure in this branch:** image
> 
> **Unit tests structure:** image

Well, it doesn't have to be similar to unit tests since the inted of e2e is to test routes only.

**Comment by nicholas-ly** [comment]
> Well, it doesn't have to be similar to unit tests since the inted of e2e is to test routes only.

Agreed though the e2e tests are (coincidentally?) named similarly to unit tests and its routes, so why not keep the consistency

**Comment by sebastien-comeau** [comment]
> > Well, it doesn't have to be similar to unit tests since the inted of e2e is to test routes only.
> 
> Agreed though the e2e tests are (coincidentally?) named similarly to unit tests and its routes, so why not keep the consistency

My bad, I thought `_app+` was a mistake.

**Pull request merged**
