### PR TITLE
Updated federal benefits page for child flow

### PR DESCRIPTION
**Pull request by AdamP-HRSDC-RHDCC**
### Description
Updated the federal provincial benefits page for the child flow from the figma design

Removed duplicate confirm translations in apply-adult-child.json

### Related Azure Boards Work Items
n/a

### Screenshots (if applicable)
image

### Checklist
- [x] I have tested the changes locally
- [x] I have updated the documentation if necessary
- [ ] I have added/updated tests that prove my fix is effective or that my feature works
- [x] I have checked that my code follows the project's coding style by running `npm run format:check`
- [x] I have checked that my code contains no linting errors by running `npm run lint`
- [x] I have checked that my code contains no type errors by running `npm run typecheck`
- [x] I have checked that all unit tests pass by running `npm run test:unit -- run`
- [x] I have checked that all e2e tests pass by running `npm run test:e2e`

### Test Instructions

comment out line 67 and 68 (invariant check)

add placeholder data, to view page

`const child = {
    id: 'id',
    dentalBenefits: {
      hasFederalBenefits: true,
      federalSocialProgram: '758bb862-26c5-ee11-9079-000d3a09d640',
      hasProvincialTerritorialBenefits: true,
      provincialTerritorialSocialProgram: 'b3f25fea-a7a9-ee11-a569-000d3af4f898',
      province: '9c440baa-35b3-eb11-8236-0022486d8d5f',
    },
    dentalInsurance: true,
  };`

### Additional Notes
n/a

### CODE REVIEW

**Comment by AdamP-HRSDC-RHDCC** [comment]
Affected commit is "Updated federal benefits page for child flow"

Not sure if I am correctly rebasing
image

**Comment by gregory-j-baker** [comment]
> Not sure if I am correctly rebasing

You want to fetch the latest commits from origin, then rebase your branch on top of those. No need to do an interactive rebase unless you need to modify your own commits.

```
git fetch
git rebase origin/main
```

**Review by gregory-j-baker — COMMENTED** [review]
Waiting for commits to be cleaned up before reviewing.

**Comment by AdamP-HRSDC-RHDCC** [comment]
> Waiting for commits to be cleaned up before reviewing.

Closed PR, will be recreated by @sebastien-comeau

**Pull request closed without merging**
